export default Object.freeze({
  APPOINTMENTS: "APPOINTMENTS",
  APPTABNAVIGATOR: "APPTABNAVIGATOR",
  CLIENT_DETAIL: "CLIENT_DETAIL",
  CLIENT_NAVIGATOR: "CLIENT_NAVIGATOR",
  CREATE_DIET_PLAN: "CREATE_DIET_PLAN",
  DIET_PLAN_TEMPLATE: "DIET_PLAN_TEMPLATE",
  HOME: "HOME",
  LOGIN: "LOGIN",
  MYCLIENTS: "MY CLIENTS",
  NOTIFICATIONS: "NOTIFICATIONS",
  OTP_INPUT_SCREEN: "OTP_INPUT_SCREEN",
  PROFILE: "PROFILE",
});
